/**
 * seed.ts
 * Populates the database with realistic Singaporean handyman data for development/demo.
 * Run: npm run seed
 */

import { initDatabase, execute, queryAll } from "./database.js";
import { v4 as uuidv4 } from "uuid";

const HANDYMEN = [
  {
    id: uuidv4(),
    name: "Ahmad Bin Yusof",
    phone: "+6591234001",
    whatsapp: "+6591234001",
    service_types: JSON.stringify(["plumbing", "hvac"]),
    location: "Tampines",
    rating: 4.8,
    bookings: 312,
    trust_score: 9.2,
    price_min: 60,
    price_max: 200,
    acra_reg: "53123456A",
    acra_status: "verified",
    bio: "15 years experience in plumbing and aircon servicing. HDB & condo specialist.",
  },
  {
    id: uuidv4(),
    name: "Sarah Lim Wei Ling",
    phone: "+6591234002",
    whatsapp: "+6591234002",
    service_types: JSON.stringify(["cleaning", "painting"]),
    location: "Jurong West",
    rating: 4.9,
    bookings: 487,
    trust_score: 9.5,
    price_min: 50,
    price_max: 150,
    acra_reg: "53234567B",
    acra_status: "verified",
    bio: "Professional cleaning and painting services. Eco-friendly products used.",
  },
  {
    id: uuidv4(),
    name: "Ravi Subramaniam",
    phone: "+6591234003",
    whatsapp: "+6591234003",
    service_types: JSON.stringify(["electrical", "carpentry"]),
    location: "Woodlands",
    rating: 4.7,
    bookings: 228,
    trust_score: 8.8,
    price_min: 80,
    price_max: 350,
    acra_reg: "53345678C",
    acra_status: "verified",
    bio: "Licensed electrician (EMA). Custom carpentry and furniture assembly.",
  },
  {
    id: uuidv4(),
    name: "John Tan Boon Kiat",
    phone: "+6591234004",
    whatsapp: "+6591234004",
    service_types: JSON.stringify(["hvac", "electrical"]),
    location: "Bishan",
    rating: 5.0,
    bookings: 156,
    trust_score: 9.8,
    price_min: 70,
    price_max: 280,
    acra_reg: "53456789D",
    acra_status: "verified",
    bio: "Aircon specialist with BCA certification. Same-day service available.",
  },
  {
    id: uuidv4(),
    name: "Amy Ng Siew Fen",
    phone: "+6591234005",
    whatsapp: "+6591234005",
    service_types: JSON.stringify(["cleaning", "plumbing"]),
    location: "Ang Mo Kio",
    rating: 4.9,
    bookings: 341,
    trust_score: 9.3,
    price_min: 55,
    price_max: 180,
    acra_reg: "53567890E",
    acra_status: "verified",
    bio: "Deep cleaning specialist. Also handles minor plumbing repairs.",
  },
  {
    id: uuidv4(),
    name: "David Chua Eng Huat",
    phone: "+6591234006",
    whatsapp: "+6591234006",
    service_types: JSON.stringify(["carpentry", "painting", "cleaning"]),
    location: "Bedok",
    rating: 4.6,
    bookings: 198,
    trust_score: 8.5,
    price_min: 65,
    price_max: 400,
    acra_reg: null,
    acra_status: "unverified",
    bio: "General handyman — carpentry, painting, and home maintenance.",
  },
  {
    id: uuidv4(),
    name: "Muthu Krishnan",
    phone: "+6591234007",
    whatsapp: "+6591234007",
    service_types: JSON.stringify(["plumbing", "electrical"]),
    location: "Yishun",
    rating: 4.5,
    bookings: 142,
    trust_score: 8.2,
    price_min: 55,
    price_max: 220,
    acra_reg: "53678901F",
    acra_status: "verified",
    bio: "Plumbing and electrical repairs for HDB flats. Fast response.",
  },
  {
    id: uuidv4(),
    name: "Linda Goh Bee Choo",
    phone: "+6591234008",
    whatsapp: "+6591234008",
    service_types: JSON.stringify(["cleaning", "painting"]),
    location: "Clementi",
    rating: 4.8,
    bookings: 267,
    trust_score: 9.0,
    price_min: 45,
    price_max: 160,
    acra_reg: "53789012G",
    acra_status: "verified",
    bio: "Move-in/move-out cleaning. Interior painting with 2-year warranty.",
  },
  {
    id: uuidv4(),
    name: "Hafiz Bin Rosli",
    phone: "+6591234009",
    whatsapp: "+6591234009",
    service_types: JSON.stringify(["gardening"]),
    location: "Pasir Ris",
    rating: 4.7,
    bookings: 134,
    trust_score: 8.6,
    price_min: 60,
    price_max: 400,
    acra_reg: "53890123H",
    acra_status: "verified",
    bio: "Landscaping, lawn care, and pruning for HDB estates and condo gardens.",
  },
  {
    id: uuidv4(),
    name: "Faridah Bte Ismail",
    phone: "+6591234010",
    whatsapp: "+6591234010",
    service_types: JSON.stringify(["general"]),
    location: "Hougang",
    rating: 4.6,
    bookings: 176,
    trust_score: 8.4,
    price_min: 40,
    price_max: 300,
    acra_reg: null,
    acra_status: "unverified",
    bio: "General handyman for drilling, mounting, sealing, and odd-job repairs.",
  },
  {
    id: uuidv4(),
    name: "Kelvin Ong Hock Seng",
    phone: "+6591234011",
    whatsapp: "+6591234011",
    service_types: JSON.stringify(["appliance"]),
    location: "Toa Payoh",
    rating: 4.8,
    bookings: 203,
    trust_score: 9.1,
    price_min: 50,
    price_max: 380,
    acra_reg: "53901234I",
    acra_status: "verified",
    bio: "Appliance repair and installation — washing machines, fridges, ovens, hoods.",
  },
  {
    id: uuidv4(),
    name: "Priya Devi Manogaran",
    phone: "+6591234012",
    whatsapp: "+6591234012",
    service_types: JSON.stringify(["smart_home"]),
    location: "Punggol",
    rating: 4.9,
    bookings: 98,
    trust_score: 8.9,
    price_min: 80,
    price_max: 650,
    acra_reg: "53012345J",
    acra_status: "verified",
    bio: "Smart lock, camera, and home automation installs across WiFi, Zigbee, and major ecosystems.",
  },
  // ─── Automotive providers (mobile + workshop) ──────────────────────────────
  {
    id: uuidv4(),
    name: "SpeedFix Auto Workshop",
    phone: "+6591234013",
    whatsapp: "+6591234013",
    service_types: JSON.stringify(["car_servicing", "car_brakes", "car_diagnostics"]),
    location: "Sin Ming (Workshop)",
    rating: 4.7,
    bookings: 264,
    trust_score: 9.0,
    price_min: 80,
    price_max: 800,
    acra_reg: "53111213K",
    acra_status: "verified",
    bio: "Full-service drive-in workshop. General servicing, brakes, and computer diagnostics for all makes.",
  },
  {
    id: uuidv4(),
    name: "Raja Mobile Mechanic",
    phone: "+6591234014",
    whatsapp: "+6591234014",
    service_types: JSON.stringify(["car_servicing", "car_battery", "car_diagnostics"]),
    location: "Island-wide (Mobile)",
    rating: 4.8,
    bookings: 189,
    trust_score: 9.1,
    price_min: 50,
    price_max: 900,
    acra_reg: "53121314L",
    acra_status: "verified",
    bio: "Mobile mechanic — I come to you. Servicing, battery replacement, and on-site diagnostics at home or office.",
  },
  {
    id: uuidv4(),
    name: "TyrePro SG",
    phone: "+6591234015",
    whatsapp: "+6591234015",
    service_types: JSON.stringify(["car_tyres", "car_brakes"]),
    location: "Ubi (Workshop + Mobile)",
    rating: 4.6,
    bookings: 312,
    trust_score: 8.8,
    price_min: 20,
    price_max: 1400,
    acra_reg: "53131415M",
    acra_status: "verified",
    bio: "Tyres, balancing, and alignment. Drive-in or mobile fitting van. Brake pads/discs on request.",
  },
  {
    id: uuidv4(),
    name: "CoolCar Aircon Specialists",
    phone: "+6591234016",
    whatsapp: "+6591234016",
    service_types: JSON.stringify(["car_aircon", "car_diagnostics"]),
    location: "Kaki Bukit (Workshop)",
    rating: 4.9,
    bookings: 147,
    trust_score: 9.2,
    price_min: 60,
    price_max: 1500,
    acra_reg: "53141516N",
    acra_status: "verified",
    bio: "Car aircon regas, compressor and condenser repair. Same-day cooling diagnosis.",
  },
  {
    id: uuidv4(),
    name: "RescueTow 24/7",
    phone: "+6591234017",
    whatsapp: "+6591234017",
    service_types: JSON.stringify(["car_towing", "car_battery"]),
    location: "Island-wide (Mobile)",
    rating: 4.5,
    bookings: 421,
    trust_score: 8.6,
    price_min: 30,
    price_max: 700,
    acra_reg: null,
    acra_status: "unverified",
    bio: "24/7 towing, roadside assistance, jumpstart and lockout. Accident recovery and cross-border tows.",
  },
];

const REVIEWS: Array<{
  handyman_index: number;
  user_id: string;
  rating: number;
  comment: string;
  service_type: string;
}> = [
  { handyman_index: 0, user_id: "user_001", rating: 5, comment: "Ahmad fixed my pipe burst at midnight. Lifesaver!", service_type: "plumbing" },
  { handyman_index: 0, user_id: "user_002", rating: 4.5, comment: "Good work on the aircon, a bit pricey.", service_type: "ac_repair" },
  { handyman_index: 1, user_id: "user_003", rating: 5, comment: "Sarah is amazing! My flat sparkles now.", service_type: "cleaning" },
  { handyman_index: 1, user_id: "user_004", rating: 5, comment: "Painting done in one day. Highly recommend!", service_type: "painting" },
  { handyman_index: 2, user_id: "user_005", rating: 4.8, comment: "Ravi rewired my kitchen safely and quickly.", service_type: "electrical" },
  { handyman_index: 3, user_id: "user_006", rating: 5, comment: "John is the best aircon guy in Singapore!", service_type: "ac_repair" },
  { handyman_index: 4, user_id: "user_007", rating: 5, comment: "Amy is thorough and professional.", service_type: "cleaning" },
  { handyman_index: 5, user_id: "user_008", rating: 4.5, comment: "David built my wardrobe perfectly.", service_type: "carpentry" },
  { handyman_index: 8, user_id: "user_009", rating: 4.5, comment: "Hafiz tidied up our overgrown garden in one afternoon.", service_type: "gardening" },
  { handyman_index: 9, user_id: "user_010", rating: 4.5, comment: "Faridah mounted our TV and shelves, very neat work.", service_type: "general" },
  { handyman_index: 10, user_id: "user_011", rating: 5, comment: "Kelvin fixed our washing machine same day.", service_type: "appliance" },
  { handyman_index: 11, user_id: "user_012", rating: 5, comment: "Priya set up our whole smart home system flawlessly.", service_type: "smart_home" },
  { handyman_index: 12, user_id: "user_013", rating: 5, comment: "SpeedFix did my major service and brakes in half a day, fair price.", service_type: "car_servicing" },
  { handyman_index: 13, user_id: "user_014", rating: 5, comment: "Raja came to my office carpark and swapped my dead battery on the spot.", service_type: "car_battery" },
  { handyman_index: 14, user_id: "user_015", rating: 4.5, comment: "TyrePro patched my puncture fast and balanced all four wheels.", service_type: "car_tyres" },
  { handyman_index: 15, user_id: "user_016", rating: 5, comment: "Aircon ice cold again after CoolCar's regas. Same day too.", service_type: "car_aircon" },
  { handyman_index: 16, user_id: "user_017", rating: 4.5, comment: "RescueTow reached me in 25 mins after a breakdown on the PIE.", service_type: "car_towing" },
];

async function seed(): Promise<void> {
  await initDatabase();

  const existing = queryAll("SELECT id FROM handymen");
  if (existing.length > 0) {
    console.log(`Database already seeded with ${existing.length} handymen. Skipping.`);
    return;
  }

  for (const h of HANDYMEN) {
    execute(
      `INSERT INTO handymen (id, name, phone, whatsapp, service_types, location, rating, bookings, trust_score, price_min, price_max, acra_reg, acra_status, bio)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [h.id, h.name, h.phone, h.whatsapp, h.service_types, h.location, h.rating, h.bookings, h.trust_score, h.price_min, h.price_max, h.acra_reg ?? null, h.acra_status, h.bio]
    );
  }

  for (const r of REVIEWS) {
    const handyman = HANDYMEN[r.handyman_index];
    execute(
      `INSERT INTO reviews (id, handyman_id, user_id, rating, comment, service_type)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [uuidv4(), handyman.id, r.user_id, r.rating, r.comment, r.service_type]
    );
  }

  console.log(`✅ Seeded ${HANDYMEN.length} handymen and ${REVIEWS.length} reviews.`);
}

seed().catch(console.error);
